env:
  global:
    TERM=dumb
language: java
jdk:
- oraclejdk8
- openjdk8
install: true
before_script:
- sudo apt udate -y || true
- sudo apt install -y curl jq python-pip || true
- sudo pip install httpie || true
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
script:
- bash ./mvnw
- bash ./gradlew
- >
  for project in \
    stock \
    starter \
  ; do
    java -jar ${project}/target/*-all.jar
    java -jar ${project}/build/libs/*-all.jar
  done;
# maven
- bash ./mvnw -pl javaee-starter clean package com.dkanejs.maven.plugins:docker-compose-maven-plugin:1.0.1:up
- sleep 30
- http :8080/javaee-starter/
- bash ./mvnw -pl javaee-starter com.dkanejs.maven.plugins:docker-compose-maven-plugin:1.0.1:down
# gradlew
- bash ./gradlew clean build :javaee-starter:composeUp
- sleep 2
- http :8080/javaee-starter/
- bash ./gradlew :javaee-starter:composeDown

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
