/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import daggerok.App;
import org.junit.Test;

public class AppTest {
  @Test
  public void testMethod() {
    App.main(new String[] {"ololo", "trololo"});
  }
}
